---
- hosts: all
  become: true
  roles:
    - create_user 
  vars:
    users:
    - username: "eakkoyun"
      groups: "admin"
    - username: "onur"
      groups: "admin"
    remove_users:
    - "emrah"
